### ISSUE TITLE
Width property is wrong

### ISSUE THREAD

**Issue by flaminestone** [ONLYOFFICE/ooxml_parser#253]
[SetWidth.docx](https://github.com/ONLYOFFICE/ooxml_parser/files/472119/SetWidth.docx)
i set "percent", 100
i get "percent", 5000
` docx.elements[1].properties.table_width`

**Comment by ShockwaveNN** [comment]
Because in `docx` file there is entry
`<w:tblW w:w="5000" w:type="pct"/>`
and pct is 1/50 of percent

`ooxml_parser` designed, that it show values like in xml in defaults
So you get "5000.0 pct" like in xml

If you wanna get it in actual, readable percent use
`docx.elements[1].properties.table_width.to_unit(:percent) => 100.0 percent`
